### ISSUE TITLE
Python example /embed/sso vs /embed

### ISSUE THREAD

**Issue by InvisibleMan1306** [looker/looker_embed_sso_examples#20]
There's some inconsistency between the different language examples around the ember url. 
In ruby and node version its "/embed/sso/dashboards/3" and in python, php and csharp its "/embed/dashboards/3", is this significant?

**Comment by npickens** [comment]
@InvisibleMan1306 The `/sso` portion of the URL was deprecated a while back and is therefore optional. `/embed/sso/dashboards/3` will just redirect to `/embed/dashboards/3`.

**Comment by InvisibleMan1306** [comment]
Thanks, that makes sense.
